### ISSUE TITLE
"type" field becomes "jhi_type" in generated table

### ISSUE THREAD

**Issue by UzverNumber47** [jhipster/jhipster-core#140]
A string "type" field became "jhi_type" column in database. 
MySQL database. Hot to specify a column name for entity field?

` @Size(max = 10)
    @Column(name = "jhi_type", length = 10)
    private String type;
`

**Comment by deepu105** [comment]
We currently do not support changing column names, you would have to edit this manually after generation

**Comment by UzverNumber47** [comment]
Why then generator translated "type" to "jhi_type"?

**Comment by jdubois** [comment]
Probably because this is a reserved keyword. We are quite strict with those, so maybe the "jhi_" prefix isn't needed, but still you should be careful when removing it.
Anyway, this is just the name of the database field, there is really no value for us in allowing to configure this (see [Policy 2(https://jhipster.github.io/policies/))
