### ISSUE TITLE
Ability to use sub-objects as view

### ISSUE THREAD

**Issue by Jumblemuddle** [jhipster/jhipster-core#16]
Not sure if this is an issue with JDL or JHipster.
```
relationship OneToOne {
    Tree{size(moon.size)} to Planet
}
```
Sorry for the bad example...

JDL won't allow the view to be a child object. (Planet has a child object 'moon' which has a size)
I've tried plenty of variations to try to get this to propogate to the Angular JS side to no avail.

Is this view used anywhere else besides on the frontend?

**Comment by deepu105** [comment]
I dont think we support this yet.

**Comment by MathieuAA** [comment]
It may be a *bad* example, but it's bloating the declaration... If we ever support something like that, a better syntax may be needed.
Moreover, I don't see a practical use cas for this. Can you give us a better example?

**Comment by Jumblemuddle** [comment]
Best case I can think of is when you want an entity with a 1-1 relationship with the User.
Naturally you'd want to display the user's login.

```
entity Profile {

}
entity Connection {
    accepted Boolean
}
relationship OneToOne {
    Profile{user(login)} to User
}
relationship OneToOne {
    Connection{initiator(user)} to Profile
}
```
It'd be nice for the 'initiator' Profile on the Connection to display the user's login instead of the object.

**Comment by Jumblemuddle** [comment]
``
relationship OneToOne {
    Connection{initiator(**user.login**)} to Profile
}
```

**Comment by deepu105** [comment]
I dont think we will do this as there is very little value for the
complications we would handle, you could easily modify the generated code
for this and this is a rare usecase

Thanks & Regards,
Deepu

**Comment by Jumblemuddle** [comment]
Very well.

Thanks

**Comment by lukewpatterson** [comment]
I'll include my workaround for anyone else who runs into this.


First, some sample JDL which gets rejected during `yo jhipster:import-jdl  <schema file>`.  The "user.login" portion causes a grammar/validation error, preventing generation:

```
entity UserProfile {
}
relationship OneToOne {
    UserProfile{user(login)} to User
}
entity Image {
    image ImageBlob
}

relationship ManyToOne {
    Image{profile(user.login)} to UserProfile
}
```

Note that the original `yo jhipster:entity`/json-based method does allow for dotted traversal in the "**otherEntityField**" entry, _thus allowing for display/sort based on a useful field in this case rather than display/sort based on a json object (think value of simply 'user', which is a json object not very nice-looking for display)_.  The json equivalent of the interesting portion of the earlier JDL sample, from .jhipster/Image.json:

```
    {
      "relationshipId": 1,
      "relationshipType": "many-to-one",
      "relationshipName": "profile",
      "otherEntityField": "user.login"
      "otherEntityName": "userProfile",
    },
```

Also note that `yo jhipster:import-jdl  <schema file>` writes the entity json files into the .jhipster directory before proceeding with the user prompts stage.


So, the workaround is:
1) Edit your jdl files, avoiding the use of dotted traversal but taking note of which entities you'll need to massage in later steps
2) Run `yo jhipster:import-jdl  <schema file>`
3) Choose 'x' to abort.  **At this point the .jhipster json files have been updated.**
4) Fix up the json files, adding in the dotted traversal parts
5) Run `for f in ``ls .jhipster``; do yo jhipster:entity ${f%.*} ; done` (or your OS' scripty equivalent) to proceed with the user prompting and generation portion

**Comment by Jumblemuddle** [comment]
Not ideal, but I do like the idea of it being the the json better than manual changes to the generated ui.
Thanks, @lukewpatterson

**Comment by deepu105** [comment]
Ok first of all I think its working in the entity generator accidentally and not intentionally :smile: so if it works then fine lets leave it like that. @MathieuAA in that case you can decide if you want to support this in JDL or not

**Comment by MathieuAA** [comment]
Hi, if it's already supported because it's has been designed, then I'll add it. If it's not, it could not work in another version and tests have to check that. What do you think, @jdubois? 

Le 11 mai 2016 05:52:51 GMT+02:00, Deepu K Sasidharan <notifications@github.com> a écrit :
>Ok first of all I think its working in the entity generator
>accidentally and not intentionally :smile: so if it works then fine
>lets leave it like that. @MathieuAA in that case you can decide if you
>want to support this in JDL or not
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-domain-language/issues/16#issuecomment-218355201

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment]
No news from anyone, so I'll close this.
