### ISSUE TITLE
Add option to entity for clientRootFolder

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-core#179]
PR https://github.com/jhipster/generator-jhipster/pull/7079 adds a new flag for entity and expects the same in entity JSON files. JDL should also specify the same while creating entity JSON files for the import-jdl sub gen

**Comment by MathieuAA** [comment]
@deepu105 Alright, I'm almost done with the addition. Can you confirm the following assumptions please?
  - If the application's type is a microservice, just ignore whatever value the user might want to set.
  - If the application's type is a gateway, use the microservice's name as value as default or the user's choice if any.
  - Otherwise, use the user's choice.

**Comment by MathieuAA** [comment]
@deepu105 (and @jdubois) I'm going to update the generator to make it use v1.4.5, and also update the subgens using the JDL so that there's no deprecation warning and also not to have any unfortunate (_but still quite funny I guess_) surprise when v2.0.0 is released.
