### ISSUE TITLE
Remove useless lodash uses

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#197]
Like the already provided `map`, `reduce`, etc. But also `isUndefined` etc.

**Comment by bd82** [comment]
I removed those you listed. I don't know what other you consider as useless...

anyhow they are not useless because:

1. Lodash methods are guaranteed to work in all envs (ES5) so I don't need to check
    MDN for compatibility before using each one. 

2. Lodash is normally read right to left (**nested calls**) while native methods are **chained** so that
    leads to inconsistency in the code base. (sometimes in the same line!)

3. Lodash methods have extra forms not supported by native methods,
    * https://lodash.com/docs#map works on arrays and objects and  can accept a callback or a **string** for simple property extraction.
   
Its your code base and your choice, but maybe its best you just modify these minor style
issues according to your preferences directly while reviewing?
