### ISSUE TITLE
Update the chevrotain parsing system for application parsing

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#198]
Some options have been removed (`useCompass` for instance, and other were added).

**Comment by MathieuAA** [comment]
@bd82 I'll be honest: it's a chore. It was painful to do it last week-end and I don't expect it to be fun now... I'll try to do it again for the new system.

**Comment by bd82** [comment]
it should be very easy because they are not listed individually in the grammar anymore.

Steps to add a config prop:
1. Define token that belong to CONFIG_KEY category -  [Code](https://github.com/jhipster/jhipster-core/blob/chevrotain-migration/lib/dsl/lexer.js#L125-L129)
2. Define its type validations - [Code](https://github.com/jhipster/jhipster-core/blob/chevrotain-migration/lib/dsl/validator.js#L78-L82)
3. Winner winner chicken dinner.
