### ISSUE TITLE
JDLLinter

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#224]
Rules to have:
  - [x] useless curly braces around entity body if there are no fields
  - [x] useless table name
  - [x] collapsible relationships (can be grouped by type)
  - [ ] useless commas separating fields
    - Commas are detected, but whitespaces are omitted
  - [ ] collapsible entity lists for options (using *, except, or just entity names)
  - [ ] empty enums (no value)
  - [ ] useless constants
  - [ ] duplicates
    - [x] entities
    - [x] fields
    - [x] enums
    - [ ] relationships
    - [ ] options
    - [ ] applications
    - [ ] constants
    - [ ] validations
  - [ ] useless application options (setting default values)
  - [x] orphan
    - [x] enum (not used)

Todo after release & PR in the generator:
  - [ ] Doc

Bonus:
  - [ ] lines (with chevrotain? :))

**Comment by bd82** [comment]
Hello @MathieuAA 😄 

I just noticed this issue and have some questions:
* Could you share links to the three rules that have been implemented already?
* Are these rules meant to implemented on the Chevrotain CST or the JDL AST (or both depending on context)?

Regarding:
> Commas are detected, but whitespaces are omitted, which makes this feature impossible

If you are referring to the parser, it is possible to collect all the whitespace instead of omitting them.
* Using [Token Groups](https://sap.github.io/chevrotain/docs/features/token_grouping.html)

Once we have all the whitespace collected, we could attach the whitespace to the CST
by using their relative positions and use that information for whitespace related lint rules.

Cheers.
Shahar.

**Comment by MathieuAA** [comment]
Ah! Awesome! I spent time looking for that without knowing what to look for, thanks!Links?Le 27 oct. 2018 01:53, Shahar Soel <notifications@github.com> a écrit :Hello @MathieuAA 😄
I just noticed this issue and have some questions:
Could you share links to the three rules that have been implemented already?Are these rules meant to implemented on the Chevrotain CST or the JDL AST (or both depending on context)?
Regarding:

Commas are detected, but whitespaces are omitted, which makes this feature impossible

If you are referring to the parser, it is possible to collect all the whitespace instead of omitting them.
Using Token Groups
Once we have all the whitespace collected, we could attach the whitespace to the CST
by using their relative positions and use that information for whitespace related lint rules.
Cheers.
Shahar.

**Comment by MathieuAA** [comment]
There's a branch for the linter, I'm not at home til tomorrow so I'll link to it tomorrow

**Comment by bd82** [comment]
Thanks I found it at:
https://github.com/jhipster/jhipster-core/tree/lint/lib/linter

I will have a look later

**Comment by MathieuAA** [comment]
Closed in favor of a GH project
