### ISSUE TITLE
Error: None Unique Grammar Name Found: <JDLParser>

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#232]
Breaks my beloved `test:watch` script =/
cc @bd82

**Comment by bd82** [comment]
Mitigation:
http://sap.github.io/chevrotain/docs/FAQ.html#MOCHA_WATCH

Will probably be resolved when I fix:
https://github.com/SAP/chevrotain/issues/754

**Comment by MathieuAA** [comment]
Can you make a PR with the `clearCache` option enabled?

**Comment by bd82** [comment]
Yes I'll try that

**Comment by bd82** [comment]
I've had a look, The mitigation offered in the FAQ is not sufficient.
It is not enough to just call clearCache, we must also avoid initializing 
any parser instance before any test executes.

This is doable but becomes quite ugly once we have to deal with CSTVisitors classes
that require the initialization of the parser to access their base class.

See: https://github.com/bd82/jhipster-core/commit/c0ca370f6f8e77f277fd54a0c6b89adae2442f6d
to get a better understanding.

It is probably best for me to prioritize and resolve SAP/chevrotain#754
and fix the root issue, I probably already spent 30% of the time needed to fix the root cause of a this specific scenario... 😢

**Comment by MathieuAA** [comment]
Okay, take your time. I'll wait for your issue to be fixed to do the release.

**Comment by bd82** [comment]
I will hopefully resolve this issue this week.
1041/1050 tests passing so far 😄

**Comment by MathieuAA** [comment]
Wow you're the best!
