### ISSUE TITLE
JDL Supporting Entities and Arrays as fields  i.e.  Book{ author Author}  Author{name String} 

### ISSUE THREAD

**Issue by delkant** [jhipster/jhipster-core#250]
##### **Overview of the feature request**
Supporting existing entities as Fields will be especially helpful for NOSql databases. where you cannot use relationships but you may want to define and generate references to other components. 

##### **Motivation for or Use Case**

I am thinking supporting references to other entities can be a generic way to work with all existing databases without having to worry too much about the user's preferences when he is selecting a DB(SQL or NOSQL).

Also, in order to make this more useful will be nice to have a way to define Set/List/Array of entities so you can define a reference to a group of records with NoSQL dbs.

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by randeepbydesign** [comment]
I don't know that this solves the core of the issue. What is needed is way to create subdocuments for entities that would not have a corresponding DAO, Repository, etc. I see two approaches we could take at the JDL level:
1. Expand the Entity grammar to support an embedded keyword: `entity Address embedded`
2. Expand the JDL Grammar to support a subdocument object: `subdocument Address`

With option 1 the issue is that all code that references entities has to account for the presence of an `embedded: true` setting to know that they should give special consideration to this special class of entity. Otherwise, modifying the parser and validation (this entity probably could not participate on the left-side of the relationship, eg). 

With Option 2 we could create .jhipster/*.json object references separately for these subdocuments so that they don't break plugins or what not. However, we would probably have to create unique relationship references for them as well.

I'm just getting started here investigating this change and any feedback is welcome. With the growing popularity of NoSQL dbs this is an important feature to have.

**Comment by MathieuAA** [comment]
Another possible way of doing that:
```
entity A {
  b EntityB required
}

@embedded // or embedded <ENTITY_LIST>
entityB {
  name String
}
```

This is not a priority right now, but this is definitely something I want to work on.

**Comment by MathieuAA** [comment]
Feel free to ping me if there's any update.

**Comment by murdos** [comment]
Just for the record, when reading this request I see some analogy with Value Object requested in #262
