### ISSUE TITLE
Setup searchEngine on the gateway if a MS has the option

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#286]
If I don't specify searchEngine elasticsearch on my gateway, the UI is generated without a search field. It seems like this should be read from the microservice apps (which have elasticsearch specified) rather than requiring it on the gateway.

**Comment by ruddell** [comment]
The `searchEngine` option is read from the entity JSON, then the search box is only generated if enabled.  This allows the developer to enable/disable for specific entities instead of all.

I dont see any issues with this using the following JDL (didn't test running, just checked for the presence of the search box in the HTML):

```
application {
    config {
        applicationType gateway
    }
    entities *
}
application {
    config {
        applicationType microservice
        baseName ms1
        searchEngine elasticsearch
    }
    entities *
}

entity Foo
entity Bar
search Foo with elasticsearch except Bar
microservice * with ms1
```

**Comment by MathieuAA** [comment]
Agreed. It's more of a "nice to have because one might forget it" than anything. That, or the fact that debugging afterwards might be troublesome.
