### ISSUE TITLE
Add JDL keyword "readonly"

### ISSUE THREAD

**Issue by hdaniel93** [jhipster/jhipster-core#318]
Hi guys.

In reference to this previous closed post https://github.com/jhipster/generator-jhipster/issues/8800

Myself and a few others on our team are thinking about working on this as its a use case thats common in our company.

Having never worked on an open source project before, can anyone point me to in the codebase some examples of a  keyword in JDL and how it effects what is generated? functionality we can use as a base? At its core its simply adding @ Immutable to the JPA class and not generating certain stuff which seems simple enough

**Comment by MathieuAA** [comment]
Hi! For this feature, you'd need:
  - to make it available in the JDL
    - as an option (readOnly * except D for instance)
    - as an annotation (@readOnly)
  - Add it to the binary options (in [this file](https://github.com/jhipster/jhipster-core/blob/master/lib/core/jhipster/binary_options.js))
  - make it exported
    - in the JDL export
    - in the JSON export
  - update the doc to add the option

---

In order to make it available in the JDL:
  - Add a new token in [the lexer](https://github.com/jhipster/jhipster-core/blob/master/lib/dsl/lexer.js) file
  - Add a validation in [the validator](https://github.com/jhipster/jhipster-core/blob/master/lib/dsl/validator.js) file
  - Add the rule in the [JDL parser](https://github.com/jhipster/jhipster-core/blob/master/lib/dsl/jdl_parser.js) file (look [here](https://github.com/jhipster/jhipster-core/blob/master/lib/dsl/jdl_parser.js#L175) for the annotation part)
  - Update the [AST builder](https://github.com/jhipster/jhipster-core/blob/master/lib/dsl/ast_builder.js) file to read only entity list

All in all, you can copy/paste the code needed for the DTO option as the readOnly option is the same:
  - it's binary (it has a value)
  - it has entities (included & excluded)

--- 

To make it exportable, there's not much to do.
As long as it's an option, just check what has been done to handle the DTO option and you'd be good to go.
As for the JSON export, it'd be good if the readOnly option accepts a boolean value.

If you need more pointers don't hesitate.

Thanks for willing to contribute :)

**Comment by hdaniel93** [comment]
@MathieuAA thanks alot! I think I know where to start, but just to clarify how/where in the jdl example on the web tool would you mark the entity country as being read only for example? https://start.jhipster.tech/jdl-studio/

**Comment by MathieuAA** [comment]
Yes I would
I have to change the default example.. it's getting a bit old.

**Comment by hdaniel93** [comment]
Oh I mean should making a file readonly in jdl look like this

@Readonly
entity Country {
	countryName String
}


or something else.


Obviously I have to do it the same way as DTO since that is the code I will be basing it on, but I am not sure how a DTO would be defined in JDL in the above example? Fairly new to JHipster

**Comment by MathieuAA** [comment]
Yeah no it's not really a binary option. More of an unary. My bad.
Just look at the skipClient option for instance.

**Comment by hdaniel93** [comment]
I have made a few changes https://github.com/hdaniel93/jhipster-core/tree/9562-ReadOnly

I see in the "contributing" section of JHipster there is information about getting NPM to use your version of the generator, how do I do similar for the core? I want to try a jhipster import-jdl ./my-jdl-file.jdl --json-only

**Comment by MathieuAA** [comment]
You must do:
  - in your fork `npm link`
  - in the generator's fork `npm link jhipster-core`

**Comment by murdos** [comment]
@hdaniel93: Hi. Are you still working on this feature? This is something I need too, so I'm willing to work on it.

**Comment by pascalgrimaud** [comment]
@murdos : the 1st ticket about this feature was opened in main generator-jhipster 8 months ago. So I think you can go ahead and take the lead. I think a big part of the work has been done but not completely finished

**Comment by MathieuAA** [comment]
Don't hesitate to ping me if you want directions :) I'm not that available nowadays but I'll make an effort.
