### ISSUE TITLE
Ability to define entity options per application

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-core#399]
##### **Overview of the feature request**

It would be great if it was possible to define [entity options](https://www.jhipster.tech/jdl/options) inside the definition of an application:

```
application {
    config {
        baseName firstMS
        applicationType microservice
        databaseType sql
        prodDatabaseType postgresql 
    }
    entities *
    paginate * with pagination
}

application {
    config {
        baseName secondMS
        applicationType microservice
        databaseType sql
        prodDatabaseType mysql 
    }
    entities *
    dto * with mapstruct
    paginate * with infinite-scroll
}

entity A
entity B
```

##### **Motivation for or Use Case**

Use different options per application.

##### **Related issues or PR**

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
HI @murdos! Yes, that'd be nice indeed! that way you could really customize what's generated.
However, in microservice architectures, you don't usually share entities (and applied options), right? so I wonder: why?

**Comment by MathieuAA** [comment]
Oh, maybe in gateways/BFFEs... No you're right, this may be needed

**Comment by Tcharl** [comment]
Hi,

Duplicating entities is a well known microservice pattern: the aggregator service.
most of the time you also duplicate backend entities in the gateway in order to avoid the latency induced by sync inter service http calls.
You then synchronize them using messaging: when the ms is updated, it sends a message in the queue that updates the gateway 'replica'.

The 'microservice patterns book explains it and you also have plenty of doc on cqrs and CDC which are pushing in that same way.

**Comment by MathieuAA** [comment]
Yeah I know, just didn't think about these ones. My previous comment reflect that somehow...

**Comment by MathieuAA** [comment]
I'm gonna POC something. I don't expect too much work, but I can already foresee some possible complications.

**Comment by MathieuAA** [comment]
An open question to you @jhipster/developers, let's say I have this simplified JDL sample:
```
application {
  config {
    ...
  }
  entities A, B
  paginate * with pagination // only A & B here
}

entity A
entity B
entity C

paginate * infinite-scroll // A, B & C
```
What should be the result?
  - Should A and B be paginated with pagination, and C with infinite-scroll?
  - Or should all the entities be paginated with infinite-scroll?

In other words which option setting should be taken into account? the global one or the one in the application's scope?
I'm leaning towards the one in the application:
  - it exists in other programming languages (the "shadowing" effect)
  - everything lives under the application scope in JHipster, and it makes sense to make them the most important "objects" in the JDL

If you agree, vote "+1". Otherwise ~don't vote~ vote "-1"

**Comment by deepu105** [comment]
+1 declaration in the application should take priority

Thanks & Regards,
Deepu

**Comment by MathieuAA** [comment]
@deepu105 agreed! that's almost done.
