### ISSUE TITLE
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain

### ISSUE THREAD

**Issue by davidweianibone** [jhipster/jhipster-core#70]
Hi, after successful boots of my project and pushing to git repository, I pulled back the project and tried running again, getting the following exception.

Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain

seems like I am missing the maven-wrapper.jar for some reason.
Any ideas ?

**Comment by MathieuAA** [comment]
Hi, this is not the place for such an issue as it doesn't (as far as I'm concerned) concern the JHispter core project. You should post this in the generator's issue tracker.
Moreover, you'd have to give us more information (the commands you did, versions, etc.).

**Comment by poolebu** [comment]
Hello! I ran into this problem also, it worked fine at first, but if cloned the project on a new folder I got the `Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain`, for me the problem was that the Github Desktop application did not recognized the `!.mvn/wrapper/maven-wrapper.jar` line of the `.gitignore` file, so the wrapper was not being versiones. **I solved it doing a commit of the `.mvn/wrapper/maven-wrapper.jar` file using the command line.**

**Comment by MathieuAA** [comment]
Interesting!
