### ISSUE TITLE
Relationships to User entity are missed when exporting Json to JDL 

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-core#79]
Obviously, I forgot this use case...

**Comment by MathieuAA** [comment]
Did you check with all the relationship types? I know that some can't be generated.

**Comment by cbornet** [comment]
I think it's just that because User is not found in the list of entities, the relationship is not created
I'm working on a fix.

**Comment by MathieuAA** [comment]
Ok! Thanks :)

**Comment by cbornet** [comment]
I think the simplest is to add the User entity by default and ignore it when printing the JDL. Are you OK with that ?

**Comment by MathieuAA** [comment]
Not really. If it's never involved in a relationship, why writing it? If I'm not mistaken, the solution would be to:
  - first check that the relationship is valid,
  - then to write the User.
Of course, if the `--no-user-management` flag is set, and the User is indeed used, then the User would have to be in the JDL.

**Comment by cbornet** [comment]
Yes, I also changed my mind and now I create a User JDLEntity that I use in relationships if needed but don't add to the JDLObject entities.
I didn't know about the  `--no-user-management` flag. I'll have a look at that...

**Comment by MathieuAA** [comment]
Well me neither. These kinds of things should be told to all JHipster devs. It's always causing me pain in the *** to find out about it later.

**Comment by cbornet** [comment]
* `skipUserManagement` is not in the UnaryOptions
* It's a global config flag that impacts the entities so it means that the server config must be parsed before the entities. This means that it should probably be enforced to pass both the config and the entities in a single method and not have two separate methods

**Comment by MathieuAA** [comment]
My bad if it's not added...

**Comment by MathieuAA** [comment]
It would be very easy to add, I think I added it in JUML.

**Comment by cbornet** [comment]
I can add it at part of the PR

**Comment by cbornet** [comment]
Oh! It's a little more complex than I thought so I'm OK if you do it :smile:

**Comment by MathieuAA** [comment]
ahahah I almost did it a while back but was interrupted. I'll try to look into during the week-end

**Comment by deepu105** [comment]
Guys every new options are either discussed on the mailing list or on a
issue ticket. I guess you need to use the watch all options to be notified

Thanks & regards,
Deepu

**Comment by MathieuAA** [comment]
This is time consuming, if I don't want to be notified of every issue the generator has it's because I don't want to know about them (I like to live in a world where there is no issue :)). And the mailing list never has sent any mail about such options.
Instead, people who add options should add options to their respective projects (I do for JUML, everybody could do it for this one).

**Comment by deepu105** [comment]
Thats difficult bro. Remember we are not a company :P
I would say in an OSS project its the contributors responsibility to keep
track of stuff. Believe it or not I pain takingly read all the emails from
all the jhipster projects :D but thats just me. Anyways this is not the
correct place for us to discuss this.
I agree that there could be a better communication option than mailing
list. Feel free to start a discussion regarding this on the mailing list. I
like the service yarn guys are using we could explore if we can use that
instead of mailing list.

Btw if my memory is correct the skip user management option was there
before we did the jhipster-core

Thanks & regards,
Deepu

On 20 Oct 2016 20:55, "Mathieu ABOU-AICHI" <notifications@github.com> wrote:

This is time consuming, if I don't want to be notified of every issue the
generator has it's because I don't want to know about them (I like to live
in a world where there is no issue :)). And the mailing list never has sent
any mail about such options.
Instead, people who add options should add options to their respective
projects (I do for JUML, everybody could do it for this one).

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jhipster/jhipster-core/issues/79#issuecomment-255138925>,
or mute the thread

**Comment by MathieuAA** [comment]
Yes, but to be up-to-date, always, is just too much. That's why I wanted a JHipster Core project...

As for the original thing of this issue, like I said, I'll try to do something this week-end and fiddle a bit with the entitiycreator here and in JUML to test a thing or two.
